channels:
- conda-forge
dependencies:
- python=3.11.8
- pip<=25.1
- pip:
  - mlflow==2.21.3
  - cloudpickle==3.1.1
  - distributed==2025.3.0
  - jinja2==3.1.5
  - lightgbm==4.6.0
  - lz4==4.4.4
  - matplotlib==3.10.0
  - numpy==2.1.3
  - pandas==2.2.3
  - pyarrow==19.0.1
  - scikit-learn==1.6.1
  - scipy==1.15.2
  - xarray==2025.1.1
  - zstandard==0.23.0
name: mlflow-env
