channels:
- conda-forge
dependencies:
- python=3.11.8
- pip<=25.1
- pip:
  - mlflow==2.21.3
  - lz4==4.4.4
  - numpy==2.1.3
  - pandas==2.2.3
  - psutil==7.0.0
  - scikit-learn==1.6.1
  - scipy==1.15.2
  - xgboost==3.0.0
name: mlflow-env
