channels:
- conda-forge
dependencies:
- python=3.11.8
- pip<=25.1
- pip:
  - mlflow==2.21.3
  - cloudpickle==3.1.1
  - lz4==4.4.4
  - numpy==1.24.4
  - pandas==2.2.3
  - psutil==7.0.0
  - scikit-learn==1.6.1
  - scipy==1.15.2
name: mlflow-env
